version: '3'

tasks:
  start:
    cmds:
      - go run main.go
  build:
    cmds:
      - rm -rf build
      - go build -o build/doctor-compose -v
      - du -h build/doctor-compose
    sources:
      - ./main.go
      - ./src/**/*
    generates:
      - ./build/doctor-compose
  bin:
    deps: [build]
    cmds:
      - ./build/doctor-compose