name: Test

on:
  push:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  test_script:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Get package
        run: go mod download && go mod vendor && go mod verify
      - name: run tests
        run: go test
      
