name: Test

on:
  push:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  test_script:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get package
        run: go mod download && go mod vendor && go mod verify
      - name: run tests
        run: go test
      
